name: pr-validation

on:
  pull_request:
    types: [opened, reopened, edited]
    branches: [main, develop]

jobs:
  pr-validation:
    uses: salesforcecli/github-workflows/.github/workflows/validatePR.yml@main
